services:

  handyboys-web:
    image: bisand/handyboys-web:latest
    volumes:
      # Data persistency
      - /mnt/docker/handyboys/web/config:/app/config
      - /mnt/docker/handyboys/web/logs:/app/logs
    restart: always
    networks:
      - 'backend-network'
      - 'internal'
    environment:
      - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}

      - NUXT_KINDE_PASSWORD=${NUXT_KINDE_PASSWORD}
      - NUXT_KINDE_CLIENT_ID=${NUXT_KINDE_CLIENT_ID}
      - NUXT_KINDE_CLIENT_SECRET=${NUXT_KINDE_CLIENT_SECRET}
      - NUXT_KINDE_AUTH_DOMAIN=${NUXT_KINDE_AUTH_DOMAIN}
      - NUXT_KINDE_REDIRECT_URL=${NUXT_KINDE_REDIRECT_URL}
      - NUXT_KINDE_LOGOUT_REDIRECT_URL=${NUXT_KINDE_LOGOUT_REDIRECT_URL}
      - NUXT_KINDE_POST_LOGIN_REDIRECT_URL=${NUXT_KINDE_POST_LOGIN_REDIRECT_URL}

      - NUXT_REDIS_HOST=${NUXT_REDIS_HOST}
      - NUXT_REDIS_PORT=${NUXT_REDIS_PORT}

      - NUXT_SERVER_ID=handyboys-web-{{.Task.Slot}}
    deploy:
      mode: replicated
      replicas: 3

  handyboys-redis:
    image: redis:latest
    networks:
      - 'internal'
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  handyboys-redis-web:
    image: marian/rebrow:latest
    networks:
      - 'internal'
    ports:
      - "5001:5001"
    restart: always
    deploy:
      mode: replicated
      replicas: 1

networks:
  internal:
    driver: overlay
  backend-network:
    external: true
